spring.application.name=coffe_server
spring.application.group=quitto
server.port=8080

server.http2.enabled=true
server.max-http-request-header-size=64KB
server.reactive.session.timeout=36000
spring.application.version=0.1v

# Logging
logging.config=classpath:logback-spring.xml
spring.output.ansi.enabled=ALWAYS

spring.config.import=optional:file:.env[.properties]

#DB Postgress
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET_API}

#Auth
api.security.key=${SERVER_API_KEY}

# Cookie (produção com HTTPS)
app.cookie.secure=true

# Spring Security
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.user-name-attribute=sub

## TLS
server.ssl.enabled=true
server.ssl.key-store=classpath:keys/server.p12
server.ssl.key-store-password=${SERVER_TLS_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.client-auth=none

#Log
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.com.quitto=DEBUG

# Spring IA
spring.ai.mcp.server.name=CoffeMCP
spring.ai.mcp.server.base-url="/mcp"
spring.ai.mcp.server.request-timeout=300
spring.ai.mcp.server.version=0.1v

# Redis
coffee.redis.enabled=true

## Redis Cache
coffee.redis.instances[0].name=cache
coffee.redis.instances[0].host=${REDIS_CACHE_HOST}
coffee.redis.instances[0].port=${REDIS_CACHE_PORT:6379}

## Redis Rate Limit
coffee.redis.instances[1].name=rate-limit
coffee.redis.instances[1].host=${REDIS_RATELIMIT_HOST}
coffee.redis.instances[1].port=${REDIS_RATELIMIT_PORT:6379}

## Pool Redis
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=16
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

# Rate Limit
coffee.ratelimit.enabled=true
