#!/bin/bash
# =============================================================================
# generate-ci-report.sh — Gera log_report.md para CI/CD
# =============================================================================
# Uso: bash scripts/generate-ci-report.sh <log_dir> <workflow> <run_id> <sha> <ref> <event>
#   [build_result] [security_result] [package_result] [integration_result]
# =============================================================================

set -euo pipefail

LOG_DIR="${1:?Missing log dir}"
WORKFLOW="${2:?Missing workflow name}"
RUN_ID="${3:?Missing run ID}"
COMMIT="${4:?Missing commit SHA}"
BRANCH="${5:?Missing branch/ref}"
EVENT="${6:?Missing trigger event}"
BUILD_RES="${7:-unknown}"
SEC_RES="${8:-unknown}"
PKG_RES="${9:-unknown}"
INT_RES="${10:-unknown}"

mkdir -p "$LOG_DIR"
NOW=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

# --- Parse Surefire ---
TEST_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0
for xml in target/surefire-reports/TEST-*.xml 2>/dev/null; do
  [ -f "$xml" ] || continue
  T=$(grep -oP 'tests="\K[0-9]+' "$xml" 2>/dev/null | awk '{s+=$1} END {print s+0}')
  F=$(grep -oP 'failures="\K[0-9]+' "$xml" 2>/dev/null | awk '{s+=$1} END {print s+0}')
  E=$(grep -oP 'errors="\K[0-9]+' "$xml" 2>/dev/null | awk '{s+=$1} END {print s+0}')
  S=$(grep -oP 'skipped="\K[0-9]+' "$xml" 2>/dev/null | awk '{s+=$1} END {print s+0}')
  TEST_COUNT=$((TEST_COUNT + T))
  FAIL_COUNT=$((FAIL_COUNT + F + E))
  SKIP_COUNT=$((SKIP_COUNT + S))
done

# --- Build report ---
cat > "$LOG_DIR/log_report.md" << EOF
# ☕ coffe_server — Log Report

**Generated:** ${NOW}
**Workflow:** ${WORKFLOW}
**Run ID:** ${RUN_ID}
**Commit:** ${COMMIT}
**Branch:** ${BRANCH}
**Trigger:** ${EVENT}

---

## Job Status

| Job | Status |
|-----|--------|
| 🛠️ Build & Test | ${BUILD_RES} |
| 🔒 Security Scan | ${SEC_RES} |
| 📦 Package | ${PKG_RES} |
| 🧪 Integration + Pentest | ${INT_RES} |

---

## ✅ Test Results

- **Total tests:** ${TEST_COUNT}
- **Failures/Errors:** ${FAIL_COUNT}
- **Skipped:** ${SKIP_COUNT}
- **Overall:** $([ "${FAIL_COUNT}" -gt 0 ] && echo "❌ FAILURE" || echo "✅ SUCCESS")

---

## 🔴 Critical Issues

$([ "${FAIL_COUNT}" -gt 0 ] && echo "- ${FAIL_COUNT} test(s) failed — check artifacts/surefire-reports/" || echo "- None detected")

## 🟡 Warnings

$([ "${SKIP_COUNT}" -gt 0 ] && echo "- ${SKIP_COUNT} test(s) were skipped" || echo "- None")

---

## 🛡️ Security Scan

- **OWASP Dependency-Check:** Check artifacts/dependency-check-report/
- **CodeQL Analysis:** Check artifacts/codeql-sarif/

### Pentest (Integration Job)

Check artifacts/app-logs/ for APP output.

---

## 💡 Improvement Ideas

- Add JaCoCo for code coverage metrics
- Configure Renovate bot for automated dependency updates
- Add performance benchmarking in CI
- Implement canary deployment strategy
- Add monitoring/alerting for build failures
- Integrate with Slack/Discord for build notifications

---

## ⏱ Execution Time

- **Report generated:** ${NOW}
- **Build Status:** ${BUILD_RES}
- **Security:** ${SEC_RES}
- **Package:** ${PKG_RES}
- **Integration:** ${INT_RES}

---

*Report auto-generated by ci-cd-pipeline agent*
EOF

echo "✅ Log report generated: $LOG_DIR/log_report.md"
